import type { Metadata } from "next";
import '@fortawesome/fontawesome-free/css/all.min.css';
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import 'bootstrap/dist/css/bootstrap.min.css';


// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
